@startuml
autonumber
participant "Система\nуправления\nскладом" as wms
participant "Среда\nпередачи\nданных" as spd

participant "Модуль\nсвязи" as conn
participant "Модуль\nшифрования/\nрасшифрования" as cypher

participant "Модуль\nобработки\nзадания" as task_maker
participant "Оркестратор\nпроцесса\nдоставки" as org
participant "Система\nнавигации" as navigation
participant "Модуль\nаварийного\nторможения" as brake #orange
participant "Модуль\nуправления\nзахватом" as grab_master

participant "Камеры" as cameras
participant "Модуль\nраспознавания\nQR-кода" as QR_detector #red
participant "Модуль\nвалидации\nсчитывания\nQR-кода" as QR_check #orange

participant "Лидары" as lidars
participant "Модуль\nконтроля\nсостояния\nлидаров" as lidars_check

participant "Система\nпередвижения" as move

participant "Модуль\nсамодиагностики" as selfdiag

participant "Контроллер\nзарядки" as battery
participant "Модуль\nконтроля\nсостояния\nзарядки" as battery_check

participant "Манипуляторы" as grab
participant "Модуль\nконтроля\nзахвата\nгруза" as grab_check

wms -> spd: зашифрованный\nзапрос товаров\nили стеллажа
spd -> conn: зашифрованный\nзапрос товаров\nили стеллажа
conn -> cypher: зашифрованный\nзапрос товаров\nили стеллажа
cypher -> task_maker: расшифрованный\nзапрос товаров\nили стеллажа
task_maker -> org: задача доставки

org -> navigation: запрос\nнавигационной\nинформации
navigation -> QR_check: запрос текущих координат
cameras -> QR_detector: фотографии
QR_detector -[#red]> QR_check: постоянные\nкоординаты\nробота (из-за\nполомки\nмодуля)
QR_check -> navigation: проверенные координаты робота
QR_check -[#green]> brake: координаты робота и данные о\nполомке модуля распознавания QR-кодов
QR_check -> selfdiag: проверенные координаты робота и данные о\nработоспособности модуля распознавания QR-кодов
navigation -> lidars_check: запрос расстояний до ближайших объектов
lidars -> lidars_check: расстояния\nдо\nпрепятствий
lidars_check -> navigation: данные о расстояниях до ближайших объектов
lidars_check -> brake: данные о работоспособности лидаров и расстояниях до ближайших объектов
lidars_check -> selfdiag: данные о работоспособности\nлидаров и расстояниях\nдо ближайших объектов
navigation -> org: навигационная\nинформация 

battery -> battery_check: текущий\nзаряд\nбатареи
battery_check -> brake: данные о состоянии заряда батареи
battery_check -> selfdiag: данные о состоянии\nзаряда батареи

org -> brake: запрос\nпередвижения/торможения
brake -[#green]> move: экстренное торможение
move -> brake: сообщение о том, что дрон едет/стоит
move -> selfdiag: сообщение о\nтом, что дрон\nедет/стоит

org -> grab_master: задание на захват/отпускание стеллажа
grab_master -> grab_check: запрос на захват/отпускание стеллажа
grab_check -> grab: команда\nзахвата/\nотпускания\nстеллажа
grab -> grab_check: данные о\nзахвате/\nотпускании\nстеллажа
grab_check -> selfdiag: данные о корректности захвата стеллажа

selfdiag -> org: данные модулей

org -> task_maker: статус\nвыполнения\nзадания
task_maker -> cypher: статус\nвыполнения\nзадания
cypher -> conn: зашифрованный\nстатус\nвыполнения\nзадания
conn -> spd: зашифрованный\nстатус\nвыполнения\nзадания
spd -> wms: зашифрованный\nстатус\nвыполнения\nзадания

@enduml