services:
  warehouse_robot:
    build: .
    image: warehouse_robot
    entrypoint:
      - venv/bin/python
      - start.py
    container_name: warehouse_robot
    environment:
      - MODULE_NAME=warehouse-robot
      - MANAGMENT_URL=http://host.docker.internal:8001  # <-- ВАЖНО!
    ports:
      - "8004:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Для Windows