@startuml
title "Негативный сценарий 15. Система захвата. Нарушение ЦБ-1, ЦБ-3, ЦБ-6, ЦБ-7"

autonumber
participant "8. WMS" as wms
participant "1. Связь" as conn
participant "2. Система\nуправления\nроботом" as ctrl
participant "5. Система координации\n(QR-коды)" as qr
participant "6. Доп. система\nкоординации\n(Лидары)" as lidar
participant "7. Система\nпередвижения" as move
participant "4. Система\nзахвата" as grip #red
participant "9. Самодиагностика" as diag

group Нормальная транспортировка
wms -> conn: команда доставки
conn -> ctrl: задача
ctrl -> grip: захват стеллажа
grip -> ctrl: захват выполнен
ctrl -> move: движение к станции
move -> move: везёт стеллаж
ctrl <- qr: координаты
ctrl <- lidar: расстояние
end

group Отказ системы захвата
note over grip
  Критическая неисправность
end note
grip -[#red]> grip: аварийное освобождение захвата
grip -[#red]> grip: **ПАДЕНИЕ стеллажа в проходе**
end

note over grip, ctrl #FFCCCC
  Робот преждевременно прекратил
  взаимодействие с заданным стеллажом.
  Выполнено сброс.
  Нарушение ЦБ-1, ЦБ-3, ЦБ-6, ЦБ-7.
end note
@enduml
